kamel:
  install:
    camel-version: 3.0.0
    runtime-version: "1.0.9-SNAPSHOT"
    maven-repositories:
    - http://192.168.178.122:8081/repository/maven-public@id=local
    - http://192.168.178.122:8081/repository/maven-public-snapshots@id=local.snpashots@snapshots@noreleases
    #- https://repository.apache.org/snapshots@id=apache.snapshots@snapshots@noreleases
    #- https://oss.sonatype.org/content/repositories/snapshots@id=oss.snapshots@snapshots@noreleases
    #- https://repository.apache.org/content/repositories/orgapachecamel-1167@id=apache.staging.camel.quarkus
  run:
    properties:
      - my.processor.message=test
    dependencies:
      # workaround for camel-quarkus not declaring camel-endpointdsl
      # in its dependencies management section
      - bom:org.apache.camel/camel-bom/3.0.0
    traits:
      - quarkus.enabled=true